name: posts_app
description: A Flutter application that displays articles.

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=3.1.3 <4.0.0"

  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  flutter_bloc: ^8.0.0
  go_router: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  path_provider: ^2.0.11
  cached_network_image: ^3.4.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true  